<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<Icon.Alien size="40" color={random_hex_color_code()} />
<Icon.Barometer size="40" color={random_hex_color_code()} />
<Icon.Celsius size="40" color={random_hex_color_code()} />
<Icon.Cloud size="40" color={random_hex_color_code()} />
<Icon.CloudDown size="40" color={random_hex_color_code()} />
<Icon.CloudRefresh size="40" color={random_hex_color_code()} />
<Icon.CloudUp size="40" color={random_hex_color_code()} />
<Icon.Cloudy size="40" color={random_hex_color_code()} />
<Icon.CloudyGusts size="40" color={random_hex_color_code()} />
<Icon.CloudyWindy size="40" color={random_hex_color_code()} />
<Icon.DayCloudy size="40" color={random_hex_color_code()} />
<Icon.DayCloudyGusts size="40" color={random_hex_color_code()} />
<Icon.DayCloudyHigh size="40" color={random_hex_color_code()} />
<Icon.DayCloudyWindy size="40" color={random_hex_color_code()} />
<Icon.DayFog size="40" color={random_hex_color_code()} />
<Icon.DayHail size="40" color={random_hex_color_code()} />
<Icon.DayHaze size="40" color={random_hex_color_code()} />
<Icon.DayLightWind size="40" color={random_hex_color_code()} />
<Icon.DayLightning size="40" color={random_hex_color_code()} />
<Icon.DayRain size="40" color={random_hex_color_code()} />
<Icon.DayRainMix size="40" color={random_hex_color_code()} />
<Icon.DayRainWind size="40" color={random_hex_color_code()} />
<Icon.DayShowers size="40" color={random_hex_color_code()} />
<Icon.DaySleet size="40" color={random_hex_color_code()} />
<Icon.DaySleetStorm size="40" color={random_hex_color_code()} />
<Icon.DaySnow size="40" color={random_hex_color_code()} />
<Icon.DaySnowThunderstorm size="40" color={random_hex_color_code()} />
<Icon.DaySnowWind size="40" color={random_hex_color_code()} />
<Icon.DaySprinkle size="40" color={random_hex_color_code()} />
<Icon.DayStormShowers size="40" color={random_hex_color_code()} />
<Icon.DaySunny size="40" color={random_hex_color_code()} />
<Icon.DaySunnyOvercast size="40" color={random_hex_color_code()} />
<Icon.DayThunderstorm size="40" color={random_hex_color_code()} />
<Icon.DayWindy size="40" color={random_hex_color_code()} />
<Icon.Degrees size="40" color={random_hex_color_code()} />
<Icon.DirectionDown size="40" color={random_hex_color_code()} />
<Icon.DirectionDownLeft size="40" color={random_hex_color_code()} />
<Icon.DirectionDownRight size="40" color={random_hex_color_code()} />
<Icon.DirectionLeft size="40" color={random_hex_color_code()} />
<Icon.DirectionRight size="40" color={random_hex_color_code()} />
<Icon.DirectionUp size="40" color={random_hex_color_code()} />
<Icon.DirectionUpLeft size="40" color={random_hex_color_code()} />
<Icon.DirectionUpRight size="40" color={random_hex_color_code()} />
<Icon.Dust size="40" color={random_hex_color_code()} />
<Icon.Earthquake size="40" color={random_hex_color_code()} />
<Icon.Fahrenheit size="40" color={random_hex_color_code()} />
<Icon.Fire size="40" color={random_hex_color_code()} />
<Icon.Flood size="40" color={random_hex_color_code()} />
<Icon.Fog size="40" color={random_hex_color_code()} />
<Icon.GaleWarning size="40" color={random_hex_color_code()} />
<Icon.Hail size="40" color={random_hex_color_code()} />
<Icon.Horizon size="40" color={random_hex_color_code()} />
<Icon.HorizonAlt size="40" color={random_hex_color_code()} />
<Icon.Hot size="40" color={random_hex_color_code()} />
<Icon.Humidity size="40" color={random_hex_color_code()} />
<Icon.Hurricane size="40" color={random_hex_color_code()} />
<Icon.HurricaneWarning size="40" color={random_hex_color_code()} />
<Icon.Lightning size="40" color={random_hex_color_code()} />
<Icon.LunarEclipse size="40" color={random_hex_color_code()} />
<Icon.Meteor size="40" color={random_hex_color_code()} />
<Icon.MoonAltFirstQuarter size="40" color={random_hex_color_code()} />
<Icon.MoonAltFull size="40" color={random_hex_color_code()} />
<Icon.MoonAltNew size="40" color={random_hex_color_code()} />
<Icon.MoonAltThirdQuarter size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningCrescent1 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningCrescent2 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningCrescent3 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningCrescent4 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningCrescent5 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningCrescent6 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningGibbous1 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningGibbous2 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningGibbous3 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningGibbous4 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningGibbous5 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaningGibbous6 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingCrescent1 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingCrescent2 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingCrescent3 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingCrescent4 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingCrescent5 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingCrescent6 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingGibbous1 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingGibbous2 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingGibbous3 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingGibbous4 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingGibbous5 size="40" color={random_hex_color_code()} />
<Icon.MoonAltWaxingGibbous6 size="40" color={random_hex_color_code()} />
<Icon.MoonFirstQuarter size="40" color={random_hex_color_code()} />
<Icon.MoonFull size="40" color={random_hex_color_code()} />
<Icon.MoonNew size="40" color={random_hex_color_code()} />
<Icon.MoonThirdQuarter size="40" color={random_hex_color_code()} />
<Icon.MoonWaningCrescent1 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningCrescent2 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningCrescent3 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningCrescent4 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningCrescent5 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningCrescent6 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningGibbous1 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningGibbous2 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningGibbous3 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningGibbous4 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningGibbous5 size="40" color={random_hex_color_code()} />
<Icon.MoonWaningGibbous6 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxing6 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingCrescent1 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingCrescent2 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingCrescent3 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingCrescent4 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingCrescent5 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingGibbous1 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingGibbous2 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingGibbous3 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingGibbous4 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingGibbous5 size="40" color={random_hex_color_code()} />
<Icon.MoonWaxingGibbous6 size="40" color={random_hex_color_code()} />
<Icon.Moonrise size="40" color={random_hex_color_code()} />
<Icon.Moonset size="40" color={random_hex_color_code()} />
<Icon.Na size="40" color={random_hex_color_code()} />
<Icon.NightAltCloudy size="40" color={random_hex_color_code()} />
<Icon.NightAltCloudyGusts size="40" color={random_hex_color_code()} />
<Icon.NightAltCloudyHigh size="40" color={random_hex_color_code()} />
<Icon.NightAltCloudyWindy size="40" color={random_hex_color_code()} />
<Icon.NightAltHail size="40" color={random_hex_color_code()} />
<Icon.NightAltLightning size="40" color={random_hex_color_code()} />
<Icon.NightAltPartlyCloudy size="40" color={random_hex_color_code()} />
<Icon.NightAltRain size="40" color={random_hex_color_code()} />
<Icon.NightAltRainMix size="40" color={random_hex_color_code()} />
<Icon.NightAltRainWind size="40" color={random_hex_color_code()} />
<Icon.NightAltShowers size="40" color={random_hex_color_code()} />
<Icon.NightAltSleet size="40" color={random_hex_color_code()} />
<Icon.NightAltSleetStorm size="40" color={random_hex_color_code()} />
<Icon.NightAltSnow size="40" color={random_hex_color_code()} />
<Icon.NightAltSnowThunderstorm size="40" color={random_hex_color_code()} />
<Icon.NightAltSnowWind size="40" color={random_hex_color_code()} />
<Icon.NightAltSprinkle size="40" color={random_hex_color_code()} />
<Icon.NightAltStormShowers size="40" color={random_hex_color_code()} />
<Icon.NightAltThunderstorm size="40" color={random_hex_color_code()} />
<Icon.NightClear size="40" color={random_hex_color_code()} />
<Icon.NightCloudy size="40" color={random_hex_color_code()} />
<Icon.NightCloudyGusts size="40" color={random_hex_color_code()} />
<Icon.NightCloudyHigh size="40" color={random_hex_color_code()} />
<Icon.NightCloudyWindy size="40" color={random_hex_color_code()} />
<Icon.NightFog size="40" color={random_hex_color_code()} />
<Icon.NightHail size="40" color={random_hex_color_code()} />
<Icon.NightLightning size="40" color={random_hex_color_code()} />
<Icon.NightPartlyCloudy size="40" color={random_hex_color_code()} />
<Icon.NightRain size="40" color={random_hex_color_code()} />
<Icon.NightRainMix size="40" color={random_hex_color_code()} />
<Icon.NightRainWind size="40" color={random_hex_color_code()} />
<Icon.NightShowers size="40" color={random_hex_color_code()} />
<Icon.NightSleet size="40" color={random_hex_color_code()} />
<Icon.NightSleetStorm size="40" color={random_hex_color_code()} />
<Icon.NightSnow size="40" color={random_hex_color_code()} />
<Icon.NightSnowThunderstorm size="40" color={random_hex_color_code()} />
<Icon.NightSnowWind size="40" color={random_hex_color_code()} />
<Icon.NightSprinkle size="40" color={random_hex_color_code()} />
<Icon.NightStormShowers size="40" color={random_hex_color_code()} />
<Icon.NightThunderstorm size="40" color={random_hex_color_code()} />
<Icon.Rain size="40" color={random_hex_color_code()} />
<Icon.RainMix size="40" color={random_hex_color_code()} />
<Icon.RainWind size="40" color={random_hex_color_code()} />
<Icon.Raindrop size="40" color={random_hex_color_code()} />
<Icon.Raindrops size="40" color={random_hex_color_code()} />
<Icon.Refresh size="40" color={random_hex_color_code()} />
<Icon.RefreshAlt size="40" color={random_hex_color_code()} />
<Icon.Sandstorm size="40" color={random_hex_color_code()} />
<Icon.Showers size="40" color={random_hex_color_code()} />
<Icon.Sleet size="40" color={random_hex_color_code()} />
<Icon.SmallCraftAdvisory size="40" color={random_hex_color_code()} />
<Icon.Smog size="40" color={random_hex_color_code()} />
<Icon.Smoke size="40" color={random_hex_color_code()} />
<Icon.Snow size="40" color={random_hex_color_code()} />
<Icon.SnowWind size="40" color={random_hex_color_code()} />
<Icon.SnowflakeCold size="40" color={random_hex_color_code()} />
<Icon.SolarEclipse size="40" color={random_hex_color_code()} />
<Icon.Sprinkle size="40" color={random_hex_color_code()} />
<Icon.Stars size="40" color={random_hex_color_code()} />
<Icon.StormShowers size="40" color={random_hex_color_code()} />
<Icon.StormWarning size="40" color={random_hex_color_code()} />
<Icon.StrongWind size="40" color={random_hex_color_code()} />
<Icon.Sunrise size="40" color={random_hex_color_code()} />
<Icon.Sunset size="40" color={random_hex_color_code()} />
<Icon.Thermometer size="40" color={random_hex_color_code()} />
<Icon.ThermometerExterior size="40" color={random_hex_color_code()} />
<Icon.ThermometerInternal size="40" color={random_hex_color_code()} />
<Icon.Thunderstorm size="40" color={random_hex_color_code()} />
<Icon.Time1 size="40" color={random_hex_color_code()} />
<Icon.Time10 size="40" color={random_hex_color_code()} />
<Icon.Time11 size="40" color={random_hex_color_code()} />
<Icon.Time12 size="40" color={random_hex_color_code()} />
<Icon.Time2 size="40" color={random_hex_color_code()} />
<Icon.Time3 size="40" color={random_hex_color_code()} />
<Icon.Time4 size="40" color={random_hex_color_code()} />
<Icon.Time5 size="40" color={random_hex_color_code()} />
<Icon.Time6 size="40" color={random_hex_color_code()} />
<Icon.Time7 size="40" color={random_hex_color_code()} />
<Icon.Time8 size="40" color={random_hex_color_code()} />
<Icon.Time9 size="40" color={random_hex_color_code()} />
<Icon.Tornado size="40" color={random_hex_color_code()} />
<Icon.Train size="40" color={random_hex_color_code()} />
<Icon.Tsunami size="40" color={random_hex_color_code()} />
<Icon.Umbrella size="40" color={random_hex_color_code()} />
<Icon.Volcano size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort0 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort1 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort10 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort11 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort12 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort2 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort3 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort4 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort5 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort6 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort7 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort8 size="40" color={random_hex_color_code()} />
<Icon.WindBeaufort9 size="40" color={random_hex_color_code()} />
<Icon.WindDeg size="40" color={random_hex_color_code()} />
<Icon.Windy size="40" color={random_hex_color_code()} />
